const PREFIX = 'COMPANIES'

export const GET_COMPANIES_REQUEST = `${PREFIX}-GET_REQUEST`
export const GET_COMPANIES_RESPONSE = `${PREFIX}-GET_RESPONSE`
export const GET_COMPANIES_ERROR = `${PREFIX}-GET_ERROR`

export const NEW_COMPANY_REQUEST = `${PREFIX}-NEW_REQUEST`
export const NEW_COMPANY_RESPONSE = `${PREFIX}-NEW_RESPONSE`
export const NEW_COMPANY_ERROR = `${PREFIX}-NEW_ERROR`
