const PREFIX = 'COMPANIES'

export const GET_COMPANIES_REQUEST = `${PREFIX}_GET_ALL_REQUEST`
export const GET_COMPANIES_RESPONSE = `${PREFIX}_GET_ALL_RESPONSE`
export const GET_COMPANIES_ERROR = `${PREFIX}_GET_ALL_ERROR`
