const PREFIX = 'COMPANIES'

export const GET_COMPANIES_REQUEST = `${PREFIX}_GET_ALL_REQUEST`
export const GET_COMPANIES_RESPONSE = `${PREFIX}_GET_ALL_RESPONSE`
export const GET_COMPANIES_ERROR = `${PREFIX}_GET_ALL_ERROR`

export const NEW_COMPANY_REQUEST = `${PREFIX}_NEW_REQUEST`
export const NEW_COMPANY_RESPONSE = `${PREFIX}_NEW_RESPONSE`
export const NEW_COMPANY_ERROR = `${PREFIX}_NEW_ERROR`
