const PREFIX = 'ORDER'

export const GET_ORDERS_REQUEST = `${PREFIX}-GET_REQUEST`
export const GET_ORDERS_RESPONSE = `${PREFIX}-GET_RESPONSE`
export const GET_ORDERS_ERROR = `${PREFIX}-GET_ERROR`

export const GET_ORDER_ITEMS = `${PREFIX}-GET_ITEMS`
export const ADD_ORDER_ITEM = `${PREFIX}-ADD_ITEM`
export const REMOVE_ORDER_ITEM = `${PREFIX}-REMOVE_ITEM`
export const FINISH_ORDER = `${PREFIX}-FINISH`

export const CANCEL_ORDER_REQUEST = `${PREFIX}-CANCEL_REQUEST`
export const CANCEL_ORDER_RESPONSE = `${PREFIX}-CANCEL_RESPONSE`
