const PREFIX = 'ORDER'

export const GET_ORDERS_REQUEST = `${PREFIX}_GET_ALL_REQUEST`
export const GET_ORDERS_RESPONSE = `${PREFIX}_GET_ALL_RESPONSE`
export const GET_ORDERS_ERROR = `${PREFIX}_GET_ALL_ERROR`
