const PREFIX = 'ORDER'

export const GET_ORDERS_REQUEST = `${PREFIX}-GET_ALL_REQUEST`
export const GET_ORDERS_RESPONSE = `${PREFIX}-GET_ALL_RESPONSE`
export const GET_ORDERS_ERROR = `${PREFIX}-GET_ALL_ERROR`

export const GET_ORDER_ITEMS = `${PREFIX}-GET_ITEMS`
export const ADD_ORDER_ITEM = `${PREFIX}-ADD_ITEM`
export const REMOVE_ORDER_ITEM = `${PREFIX}-REMOVE_ITEM`
export const DONE_ORDER = `${PREFIX}-DONE`
